replicaCount: 2

observatoryimage:
  repository: andrewkrug/httpobs
  tag: latest
  pullPolicy: IfNotPresent

observatorydbimage:
  repository: andrewkrug/httpobs-db
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 57001

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  enabled: true
  postgresUser: httpobs
  postgresPassword: totallyfakepassword
  postgresDatabase: http_observatory

observatory:
  redis_broker_url: redis://redis:6379/0
  scanner_database_host: postgres
  scanner_database_password: httpobsscannerpassword
  scanner_maximum_concurrency: 16
  scanner_number_replicas: 2
  web_container_port: 57001
  web_container_workers: 8
