apiVersion: v1
kind: Service
metadata:
  name: {{ template "httpobs.fullname" . }}-webserver
  labels:
    app: {{ template "httpobs.name" . }}
    chart: {{ template "httpobs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.observatory.web_container_port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "httpobs.name" . }}-webserver
    release: {{ .Release.Name }}
